name: Test
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        poetry-version: ["1.5.0"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    env: 
      FLASK_SECRET_KEY: ${{ secrets.FLASK_SECRET_KEY }}
    steps:
      - name: Clone the project
        uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
         
      - name: Install project
        run: poetry install --no-root

      - name: Run tests
        run: poetry run task test
